name: "Update Embedded KARTE SDK"
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      id-token: write
    steps:
      #- name: Cancel Previous Runs
      #  uses: styfle/cancel-workflow-action@0.9.1
      #  with:
      #    access_token: ${{ secrets.GH_ACCESS_TOKEN }}
      #
      - name: Set up ruby 
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '3.1'
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: feature/auto_upgrade_embdded_libraries
      - name: Checkout karte-ios-sdk
        uses: actions/checkout@v3
        with:
          repository: plaidev/karte-ios-sdk
          ref: master
          path: karte-ios-sdk
      - name: Configure Git
        run: |
          git config user.email "git@users.noreply.github.com"
          git config user.name "github actions"
      - name: Downlaod Jars
        run: ruby scripts/ci/update_android_dependencies.rb
      - name: git status
        run: |
          git status
          git diff
      - name: pod install
        run: |
          cd karte-component/src/ios-unified/source/KarteXamarin
          pod install
          cd -
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app'
      - name: Create fat binaries
        run: |
          bash ./scripts/ci/build-fat.sh
      - name: git commit & push
        run: |
          git checkout -b chore/update_karte_sdk
          git add .
          git commit -m "Update Karte SDK"
          git push origin chore/update_karte_sdk
